### ISSUE TITLE
[FEATURE] 18Lilliput

### ISSUE THREAD

**Issue by anupinka** [Stinolez/Tabletop-Helper#21]
**Is this general or board game related feature?**
Implement game 18Lilliput:
<https://boardgamegeek.com/boardgame/250621/18lilliput>.

**Describe what should the feature do**
Shuffle companies + shuffle personalities

Logo:
![18Lilliput-Rulebook-CZ-web-01](https://user-images.githubusercontent.com/61150005/75148348-b44fcf80-56ff-11ea-9830-0440d22b221b.jpg)

Companies:
![zakladni spolecnosti](https://user-images.githubusercontent.com/61150005/75148110-21af3080-56ff-11ea-9001-4edd95fe8ffd.jpg)

Personalities:
![osobnosti](https://user-images.githubusercontent.com/61150005/75148118-28d63e80-56ff-11ea-94a1-f899c634d9f0.jpg)

**Comment by Stinolez** [comment]
Functionality ready.
Waiting to process and finalize the graphic of the game elements and logo for the app.

Expected release: 28th or 29th February 2020.

**Comment by Stinolez** [comment]
Release in 2.2.200228
